export const signupDict: Dictionary = {
  th: {
    title: "สร้าง Kraikub ID ของคุณ",
    note: "บัญชีสำหรับบุคคลภายนอก",
    "first-name": "ชื่อจริง",
    "last-name": "นามสกุล",
    email: "อีเมล",
    "email-description": "(อีเมลยืนยันจะถูกส่งไปที่นี่)",
    "account-type-question": "ต้องการใช้บัญชีนี้ในนามของ",
    "select-placeholder": "เลือกประเภท",
    personal: "บัญชีส่วนตัว (ไม่ใช่นิสิต/นักศึกษา)",
    corporate: "องค์กร",
    "btn-continue": "ดำเนินการต่อ",
    "Email may be used bu another user.": "อีเมลนี้ถูกใช้งานโดยผู้อื่นแล้ว",
    username: "ชื่อผู้ใช้งาน",
    "username-placeholder": "เช่น john.12 หรือ john_12",
    "Invalid username pattern (regex test failed)":
      "ชื่อผู้ใช้งานประกอบไปด้วยตัวอักษรที่ไม่อนุญาต",
    "Username already taken": "ชื่อผู้ใช้งานถูกใช้ไปแล้ว",
  },
  en: {
    title: "Create your Kraikub ID",
    note: "Non-student Account",
    "first-name": "First name",
    "last-name": "Last name",
    email: "Email",
    "email-description": "(A verification email will be sent)",
    "account-type-question": "You want to use this account as",
    "select-placeholder": "Select account type",
    personal: "Personal account (Non-student)",
    corporate: "Corporate/Organization",
    "btn-continue": "Continue",
    "Email may be used bu another user.":
      "Email is being used by another user.",
    username: "Username",
    "username-placeholder": "Ex john.12 หรือ john_12",
    "Invalid username pattern (regex test failed)": "Invalid username pattern.",
    "Username already taken": "Username already taken",
  },
};
